name: OtoWave
description: "OtoWave project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

  flutter_icons:
    image_path: "assets/icon/icon.png"
    android: true
    ios: true

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/icon/
     - assets/splash/

  fonts:
     - family: Inter-Medium
       fonts:
         - asset: fonts\Inter-Medium.ttf